### ISSUE TITLE
Doplněk úplně přestal fungovat

### ISSUE THREAD

**Issue by weits** [kodi-czsk/plugin.video.dmd-czech.aktualne#17]
Zobrazí se pouze hláška Chyba doplňku, podrobnosti najdete v logu. Kodi 18.2 na Ubuntu 18.04. Nezobrzí se ani seznam videí.

**Comment by JALedebour** [comment]
Kodi 18(Lea) na OSMC stejný problém. 
LOG:
`2019-06-12 10:04:10.302 T:1510757088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.dmd-czech.aktualne/addon.py", line 259, in <module>
                                                listShows()
                                              File "/home/osmc/.kodi/addons/plugin.video.dmd-czech.aktualne/addon.py", line 194, in listShows
                                                con = urllib2.urlopen(request)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
2019-06-12 10:04:10.441 T:1656738528   ERROR: GetDirectory - Error getting plugin://plugin.video.dmd-czech.aktualne/
2019-06-12 10:04:10.444 T:1916073520   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dmd-czech.aktualne/) failed
2019-06-12 10:04:10.772 T:1648345824  NOTICE: ["Initializing provider czsklib with settings {'lang': '0', 'downloads': '/media/36FE2A05FE29BDCD/', 'quality': ''}"]
2019-06-12 10:04:10.773 T:1648345824  NOTICE: ['SC Service Started']
2019-06-12 10:05:12.668 T:1692373728   ERROR: EXCEPTION: Non-Existent Control 300
2019-06-12 10:06:37.844 T:1604305632  NOTICE: ES: Client  from ::ffff:10.0.0.120 timed out`

**Comment by me2d09** [comment]
Opraveno, otestujte jestli vám to funguje.

**Comment by JALedebour** [comment]
Funguje, díky :).

**Comment by me2d09** [comment]
Super, zvýšil jsem verzi, takže by se měl doplněk časem všude upgradovat.
