### ISSUE TITLE
Nefunkční přehrávání

### ISSUE THREAD

**Issue by StepanOrt** [kodi-czsk/plugin.video.dmd-czech.aktualne#2]
Nelze přehrávat žádné video

**Comment by starenka** [comment]
Nevim, jestli to souvisi s timhle fixem, ale porad to nejde... 

```
02:17:35 3201455.500000 T:1503863872  NOTICE: -->Python Interpreter Initialized<--
02:17:38 3201458.500000 T:1503863872 WARNING: Attempt to use invalid handle -1
02:17:42 3201462.750000 T:1503863872   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.dmd-czech.aktualne/addon.py", line 258, in <module>
                                                playUrl(url)
                                              File "/storage/.kodi/addons/plugin.video.dmd-czech.aktualne/addon.py", line 153, in playUrl
                                                url = re.compile('file: ?\'([^\']*?)\'').search(version).group(1).strip()
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--

```

**Comment by ToKroCZ** [comment]
@starenka Podle mě to ještě není "vydané", též mi to pořád nefunguje.
