### ISSUE TITLE
Nefunkcni plugin (Kodi Leia)

### ISSUE THREAD

**Issue by robiecz** [kodi-czsk/plugin.video.dmd-czech.aktualne#20]
Ahoj,
cista instalace Kodi, ani po rebootu nefunguje, toto jsme vytahnul z logu.
Zkousel jsem i jine porady, nefunguje nic. :-(
Rad pomuzu s testovanim.

2021-04-20 08:55:30.856 T:3609194720   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.aktualne.cz/main.py", line 3, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.aktualne.cz/resources/lib/plugin.py", line 118, in run
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.aktualne.cz/resources/lib/plugin.py", line 85, in get_video
                                                data = json.loads(re.search(r'BBXPlayer.setup\(\s+(.*)', soup.get_text().encode('utf-8')).group(1))
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
2021-04-20 08:55:31.130 T:4070091968   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.aktualne.cz/get_video/https://video.aktualne.cz/dvtv/hamacek-lze-chtel-si-splhnout-u-zemanovych-volicu-jeho-vykon/r~0b8104cca15511ebaedf0cc47ab5f122/?utm_source=mediafed&utm_medium=rss&utm_campaign=mediafed]

**Comment by ondrejbima** [comment]
Mam to fixnuty u [sebe](https://github.com/beam-kodi-addons-repository/plugin.video.aktualne.cz/releases) pripadne muzes aktualizovat pres [repositar](https://github.com/beam-kodi-addons-repository/repository-packages)
